"""Gom bản web tĩnh vào dist/ để đưa lên GitHub Pages: game (game/dist) + viewer + GLB đã nén.

Chạy: python scripts/make_site.py            (tự build game: npm --prefix game run build)
      python scripts/make_site.py --no-build (dùng game/dist có sẵn)
dist/ là git worktree của nhánh gh-pages (repo thanhdo257205/fville-onboard; nhánh main = mã nguồn).
Máy mới: git worktree add dist gh-pages. Script giữ nguyên dist/.git (file trỏ về worktree).
Commit + push bản build: python scripts/deploy_site.py (chỉ khi người dùng đồng ý đưa bản mới lên mạng).

Được đưa lên: game đã build, viewer, GLB bối cảnh, GLB nhân vật (Prajith đã được duyệt), data/*.json.
KHÔNG BAO GIỜ đưa lên: FBX gốc từ Mixamo (điều khoản Mixamo không cho phát tán animation dạng thô), file .blend,
thư mục source/ và mixamo/ của nhân vật, .raw.glb, references/ (video, ảnh thật), renders/, TASK.md, REPORT.md.
"""
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DIST = ROOT / "dist"
ZONES = ["zone_00_pickup", "zone_01_bus", "zone_02_campus", "zone_03_lobby", "zone_04_corridor", "zone_05_office"]
TIERS = ("low",)  # viewer: bản cao tạm dừng (2026-10-08). Game tự mang GLB 2 mức trong dist/game/.

INDEX = """<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>First Day at F-Ville</title>
<style>
  body { margin: 0; min-height: 100vh; display: grid; place-content: center; gap: 18px; text-align: center;
         background: #1b1e24; color: #f4f5f7; font: 16px/1.5 system-ui, "Segoe UI", sans-serif; }
  h1 { margin: 0; font-size: 30px; }
  a { display: inline-block; margin: 6px; padding: 12px 22px; border-radius: 12px; text-decoration: none; font-weight: 700; }
  .play { background: #f37021; color: #fff; } .viewer { background: #2a2e36; color: #f4f5f7; }
</style></head>
<body><h1>First Day at F-Ville</h1>
<div><a class="play" href="game/">Play</a><a class="viewer" href="viewer/">Scene viewer</a></div>
</body></html>
"""

README = """# F-Ville 1 — First Day at F-Ville (built site)

This branch (`gh-pages`) is the GitHub Pages build. Source code: branch `main`.

- `game/` — the web game (vertical slice: city bus stop → zone 3), built with Vite + Three.js.
- `viewer/` — scene viewer for the low-poly F-Ville 1 zones.

Character models made with Meshy (meshy.ai), CC BY 4.0. Rigging and animation: Adobe Mixamo.
Generated by `scripts/make_site.py`, published by `scripts/deploy_site.py`.
"""

BLOCK = (".fbx", ".blend", ".blend1", ".raw.glb")
BLOCK_PARTS = {"source", "mixamo", "references", "renders"}


def copy(src, dst):
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)


def check_worktree():
    """dist/ phải là worktree của nhánh gh-pages (không thì build ra sẽ không commit/push được đúng chỗ)."""
    if not (DIST / ".git").exists():
        raise SystemExit("DỪNG: dist/ chưa là git worktree — chạy: git worktree add dist gh-pages")
    r = subprocess.run(["git", "-C", str(DIST), "rev-parse", "--abbrev-ref", "HEAD"], capture_output=True, text=True)
    if r.stdout.strip() != "gh-pages":
        raise SystemExit(f"DỪNG: dist/ đang ở nhánh '{r.stdout.strip()}', cần gh-pages")


def main():
    check_worktree()
    if "--no-build" not in sys.argv:
        r = subprocess.run("npm --prefix game run build", shell=True, cwd=ROOT, capture_output=True, text=True,
                           encoding="utf-8", errors="replace")
        if r.returncode != 0:
            print(r.stdout[-3000:], r.stderr[-3000:])
            raise SystemExit("DỪNG: build game lỗi")
    game_dist = ROOT / "game" / "dist"
    if not (game_dist / "index.html").exists():
        raise SystemExit("DỪNG: chưa có game/dist — chạy lại không có --no-build")

    for p in DIST.iterdir():  # dọn bản cũ, giữ dist/.git (file trỏ về worktree)
        if p.name == ".git":
            continue
        shutil.rmtree(p) if p.is_dir() else p.unlink()

    # game (tự chứa GLB 2 mức, nhân vật, data)
    shutil.copytree(game_dist, DIST / "game")
    # viewer + GLB bối cảnh + nhân vật cho chế độ "Nhân vật tại NPC_"
    copy(ROOT / "viewer" / "index.html", DIST / "viewer" / "index.html")
    for tier in TIERS:
        for z in ZONES:
            copy(ROOT / "assets" / "glb" / tier / f"{z}.glb", DIST / "assets" / "glb" / tier / f"{z}.glb")
    copy(ROOT / "data" / "characters.json", DIST / "data" / "characters.json")
    for d in (ROOT / "assets" / "characters").iterdir():
        for g in d.glob(f"{d.name}*.glb"):
            if not g.name.endswith(".raw.glb"):
                copy(g, DIST / "assets" / "characters" / d.name / g.name)
    (DIST / "index.html").write_text(INDEX, encoding="utf-8")
    (DIST / "README.md").write_text(README, encoding="utf-8")
    (DIST / ".nojekyll").write_text("", encoding="utf-8")  # GitHub Pages phục vụ file nguyên trạng

    files = sorted(p.relative_to(DIST).as_posix() for p in DIST.rglob("*") if p.is_file() and ".git" not in p.parts)
    leaked = [f for f in files if f.lower().endswith(BLOCK) or BLOCK_PARTS & set(f.split("/"))]
    if leaked:
        shutil.rmtree(DIST / "game", ignore_errors=True)
        raise SystemExit(f"DỪNG: file không được công khai lọt vào dist/: {leaked}")
    size = sum((DIST / f).stat().st_size for f in files)
    chars = [f for f in files if "/characters/" in f]
    print(f"{len(files)} file, {size / 1024 / 1024:.1f} MB → {DIST}")
    print("nhân vật:", chars)


if __name__ == "__main__":
    main()
